### ISSUE TITLE
News And Events, Main page, we need to add scroll to the side

### ISSUE THREAD

**Issue by yodabro** [yodabro/olivehillgroup#1]
So we can be adding 4,5,6 and etc news and they would just scroll to your right for example.

Also, overall sizing and positioning for this 3 columns is slightly off, maybe you know how to fix it fast.

**Comment by Bran99** [comment]
This can be done w/ css.  Set the news section to
```position: fixed;
right: 0;
top: 0;
left: 0;
max-height: calc(100vh - *the height of the navbar*);
overflow-y: scroll;
-webkit-overflow-scrolling: touch;
```

Then add a right margin to the rest of the content equal to the width of the news section (unless they're bootstrap columns, which are already floated left).
